<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="Common.Logging" Version="3.4.1" />
    <PackageReference Include="Common.Logging.Core" Version="3.4.1" />
    <PackageReference Include="Common.Logging.Log4Net1210" Version="3.4.1" />
    <PackageReference Include="log4net" Version="1.2.10" />
    <PackageReference Include="Nancy" Version="2.0.0" />
    <PackageReference Include="Nancy.Hosting.Self" Version="2.0.0" />
    <PackageReference Include="Spring.Aop" Version="3.0.2" />
    <PackageReference Include="Spring.Core" Version="3.0.2" />
    <PackageReference Include="Spring.Data" Version="3.0.2" />
    <PackageReference Include="Spring.Data.NHibernate5" Version="3.0.2" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.115.5" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config\**\*.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="mapping\**\*.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="database\**\*.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
